services:
  spark-master:
    image: apache/spark:3.5.4
    container_name: spark-master
    command: /opt/spark/sbin/start-master.sh
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"   # Master UI
      - "7077:7077"   # Master RPC
    volumes:
      - ./data:/opt/spark-data
      - ./spark-events:/opt/spark-events
      - ./target/scala-2.12:/opt/spark-app

  spark-worker-1:
    image: apache/spark:3.5.4
    container_name: spark-worker-1
    command: /opt/spark/sbin/start-worker.sh spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark-data
      - ./spark-events:/opt/spark-events
      - ./target/scala-2.12:/opt/spark-app

  spark-worker-2:
    image: apache/spark:3.5.4
    container_name: spark-worker-2
    command: /opt/spark/sbin/start-worker.sh spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark-data
      - ./spark-events:/opt/spark-events
      - ./target/scala-2.12:/opt/spark-app

  spark-history-server:
    image: apache/spark:3.5.4
    container_name: spark-history-server
    command: /opt/spark/sbin/start-history-server.sh
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark-events
    ports:
      - "18080:18080"  # History Server UI
    depends_on:
      - spark-master
    volumes:
      - ./spark-events:/opt/spark-events
